-- =============================================
-- MIGRATION: Add suggested_aeo_prompts to projects
-- Description: Add JSONB column to store AEO prompts suggested by analyze-brand-website
-- Date: 2025-12-24
-- =============================================

-- Add suggested_aeo_prompts column (JSONB)
ALTER TABLE projects 
ADD COLUMN IF NOT EXISTS suggested_aeo_prompts JSONB DEFAULT NULL;

-- Add comment for documentation
COMMENT ON COLUMN projects.suggested_aeo_prompts IS 
'JSONB structure containing AEO prompt suggestions generated by analyze-brand-website. 
Structure: { categories: [{ name: string, prompts: [{ text: string, order: number }] }], generated_at: timestamp }';

-- Create index for filtering projects with suggested prompts
CREATE INDEX IF NOT EXISTS idx_projects_suggested_aeo_prompts 
ON projects USING GIN (suggested_aeo_prompts) 
WHERE suggested_aeo_prompts IS NOT NULL;

